### ISSUE TITLE
Full Support For VRDR Messaging

### ISSUE THREAD

**Issue by MikeRileyGTRI** [MortalityReporting/VRDR_javalib#4]
* Review Messaging standard here: http://build.fhir.org/ig/nightingaleproject/vital_records_fhir_messaging_ig/branches/main/index.html
* Create a package for messaging separate from the model (Try and replicate the framework of model/utils/context)
* Create VRDRFHIRContext WITH messaging resources
* Create example test cases using each messaging exchange pattern described in the guide at http://build.fhir.org/ig/nightingaleproject/vital_records_fhir_messaging_ig/branches/main/message.html#message-exchange-patterns

**Comment by pkmitre** [comment]
The VRDR Java library would ideally have functional parity with the VRDR .NET Messaging library at https://github.com/nightingaleproject/vrdr-dotnet/tree/master/VRDR.Messaging

**Comment by MikeRileyGTRI** [comment]
Just to add to Pete's comment, should have test fixtures equivalent to to dotnet's as well. https://github.com/nightingaleproject/vrdr-dotnet/tree/master/VRDR.Tests
